### ISSUE TITLE
Installation command doesn't work in README

### ISSUE THREAD

**Issue by Dcampb007** [DLR-SC/provneo4j-api#6]
pip install provneo4j-api doesn't work when I tried. However, pip install provneo4j does work. 

Just thought I'd share.

**Comment by B-Stefan** [comment]
Thanks for the information. 
I changed the [typo](https://github.com/DLR-SC/provneo4j/commit/ada363168c287f21a58a061d4a6f594f74f29310#diff-04c6e90faac2675aa89e2176d2eec7d8) in the readme.
